// Generated by bulloak

/// Context for test conditions
#[derive(Default)]
struct TestContext {
    // Add fields as needed
}

/// Helper: When first arg is smaller than second arg
fn first_arg_is_smaller_than_second_arg(mut ctx: TestContext) -> TestContext {
    // TODO: Set up condition
    ctx
}

/// Helper: When first arg is bigger than second arg
fn first_arg_is_bigger_than_second_arg(mut ctx: TestContext) -> TestContext {
    // TODO: Set up condition
    ctx
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[should_panic]
    fn test_should_never_panic() {
        // It should never panic.
    }

    #[test]
    fn test_first_arg_is_smaller_than_second_arg_should_match_the_result_of_hashab() {
        let _ctx = first_arg_is_smaller_than_second_arg(TestContext::default());
        // It should match the result of hash(a, b).
    }

    #[test]
    fn test_first_arg_is_bigger_than_second_arg_should_match_the_result_of_hashba() {
        let _ctx = first_arg_is_bigger_than_second_arg(TestContext::default());
        // It should match the result of hash(b, a).
    }

}
