// Generated by bulloak

/// Context for test conditions
#[derive(Default)]
struct TestContext {}
/// Helper: when formatting toggled
fn formatting_toggled(mut ctx: TestContext) -> TestContext {
    ctx
}
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn test_when_formatting_toggled() {
        let _ctx = formatting_toggled(TestContext::default());
        // it should reformat comment
        // it should handle question?
    }
}

