// Generated by bulloak

/// Context for test conditions
#[derive(Default)]
struct TestContext {}
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn test_cant_dox() {
        // It can’t do, X.
    }
}

