// Generated by bulloak

/// Context for test conditions
#[derive(Default)]
struct TestContext {}
/// Helper: When stuff is called
fn stuff_is_called(mut ctx: TestContext) -> TestContext {
    ctx
}
/// Helper: When a condition is met
fn a_condition_is_met(mut ctx: TestContext) -> TestContext {
    ctx
}
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    #[should_panic]
    fn test_when_a_condition_is_met() {
        let _ctx = a_condition_is_met(stuff_is_called(TestContext::default()));
        // It should revert.
    }
}

