// Generated by bulloak

struct TestContext {}

// Missing: fn condition_is_met(mut ctx: TestContext) -> TestContext {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_when_condition_is_met() {
        let _ctx = condition_is_met(TestContext::default());
        // It should work.
    }
}
