// Generated by bulloak

struct TestContext {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_should_work() {
        // It should work.
    }
    // Missing: test_should_also_work_differently
}
