// Generated by bulloak

struct TestContext {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[should_panic]
    fn test_should_work_normally() {
        // It should work normally.
    }
}
